SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
GAME_FPS = 60

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_MAX_SPEED = 420
PLAYER_THRUST = 260
PLAYER_DRAG = 0.5
PLAYER_FORWARD_FACTOR = 1.0
PLAYER_REVERSE_FACTOR = 0.6
PLAYER_MUZZLE_OFFSET = 6

PLAYER_SHOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3

SHOT_RADIUS = 5
